/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SimCCS;

import org.junit.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        System.out.println("Hello world");
    }
}
